from __future__ import annotations

import os
import re
import tempfile
from collections.abc import Generator
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any, TextIO
from zipfile import ZIP_DEFLATED, ZipFile

from src.core.mtk_port.boot_image import repack_bootimg, unpack_bootimg


class UnsafeArchiveMemberError(ValueError):
    """Raised when a ZIP member would escape the extraction directory."""


class PropertyFile:
    """Read and update a simple Android property file transactionally."""

    def __init__(self, prop_file: str | os.PathLike[str]):
        self.path = Path(prop_file)
        if not self.path.exists():
            raise FileNotFoundError(f'Property file does not exist: {self.path}')
        self.prop = {name: value for name, value in self._load_properties()}
        self._dirty = False

    def _load_properties(self) -> Generator[tuple[str, str], Any, None]:
        with self.path.open('r', encoding='utf-8') as file_handle:
            for line in file_handle:
                stripped = line.strip()
                if not stripped or stripped.startswith('#') or '=' not in line:
                    continue
                name, value = line.rstrip('\n').split('=', 1)
                yield name, value

    def get(self, key: str) -> str:
        return self.prop.get(key, '')

    def set(self, key: str, value: object) -> None:
        normalized_value = str(value)
        if self.prop.get(key) == normalized_value:
            return
        self.prop[key] = normalized_value
        self._dirty = True

    def save(self) -> None:
        if not self._dirty:
            return

        original_mode = self.path.stat().st_mode
        temporary_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                mode='w',
                encoding='utf-8',
                newline='\n',
                dir=self.path.parent,
                prefix=f'.{self.path.name}.',
                suffix='.tmp',
                delete=False,
            ) as file_handle:
                temporary_path = Path(file_handle.name)
                for key, value in self.prop.items():
                    file_handle.write(f'{key}={value}\n')
                file_handle.flush()
                os.fsync(file_handle.fileno())
            os.chmod(temporary_path, original_mode)
            os.replace(temporary_path, self.path)
            self._dirty = False
        finally:
            if temporary_path is not None and temporary_path.exists():
                temporary_path.unlink()

    def __enter__(self) -> 'PropertyFile':
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> bool:
        if exc_type is None:
            self.save()
        return False


class UpdaterScript:
    """Parse and regenerate Android updater-script metadata commands."""

    def __init__(self, file_handle: TextIO):
        if file_handle is None:
            raise ValueError('Updater script file handle is required')
        self.fd = file_handle
        self.content = self._parse_commands()

    def _parse_commands(self) -> list[list[str]]:
        self.fd.seek(0)
        commands = re.findall(r'(\w+)\((.*?)\)', self.fd.read().replace('\n', ''))
        return [
            [command, *(arg[0] or arg[1] or arg[2] for arg in re.findall(r'(?:(?:"([^"]+)")|(\b\d+\b)|(\b\S+\b))', args))]
            for command, args in commands
        ]

    def generate(self, author: str, version: str, partitions: dict) -> str | None:
        def quote(arg: str) -> str:
            return arg if arg.isdigit() else f'"{arg}"'

        system_partition = partitions.get('system')
        boot_partition = partitions.get('boot')
        if not system_partition or not boot_partition:
            return None
        self.fd.seek(0)
        commands = re.findall(r'(\w+)\((.*?)\)', self.fd.read().replace('\n', ''))
        filtered_commands = [
            (command, *(arg[0] or arg[1] or arg[2] for arg in re.findall(r'(?:(?:"([^"]+)")|(\b\d+\b)|(\b\S+\b))', args)))
            for command, args in commands
            if command in {'symlink', 'set_metadata_recursive', 'set_metadata'}
        ]
        metadata_commands = [
            f"{command}({', '.join(map(quote, args))});"
            for command, *args in filtered_commands
        ]
        lines = [
            'ui_print("");',
            'ui_print("======== Auto Generated By MTK PORT TOOL ========");',
            f'ui_print("- Author: {author}");',
            f'ui_print("- Version: {version}");',
            'ui_print("- MTK PORT TOOL Info below:");',
            'ui_print("=================================================");',
            'ifelse(is_mounted("/system"), unmount("/system"));',
            f'run_program("mke2fs", "{system_partition}");',
            f'format("ext4", "EMMC", "{system_partition}", "0", "/system");',
            'set_progress(0.1);',
            'ui_print("- Mounting system partition...");',
            f'mount("ext4", "EMMC", "{system_partition}", "/system", "max_batch_time=0,commit=1,data=ordered,barrier=1,errors=panic,nodelalloc");',
            'ui_print("- Extract system conditionally...");',
            'set_progress(0.2);',
            'package_extract_dir("system", "/system");',
            'set_progress(0.5);',
            'ui_print("- Create symlinks and setup metadata...");',
            *metadata_commands,
            'set_progress(0.8);',
            'ui_print("- Flash boot image...");',
            f'package_extract_file("boot.img", "{boot_partition}");',
            'set_progress(0.9);',
            'ui_print("- Done!");',
            'unmount("/system");',
            'set_progress(1);',
        ]
        return '\n'.join(lines)


def _validate_archive_member(member_name: str, destination: Path) -> None:
    normalized_name = member_name.replace('\\', '/')
    posix_path = PurePosixPath(normalized_name)
    windows_path = PureWindowsPath(member_name)
    if (
        not normalized_name
        or posix_path.is_absolute()
        or windows_path.is_absolute()
        or windows_path.drive
        or '..' in posix_path.parts
    ):
        raise UnsafeArchiveMemberError(f'Unsafe ZIP member path: {member_name!r}')

    target = (destination / Path(*posix_path.parts)).resolve()
    try:
        target.relative_to(destination)
    except ValueError as exc:
        raise UnsafeArchiveMemberError(f'ZIP member escapes extraction directory: {member_name!r}') from exc


def safe_extract_zip(archive: ZipFile, destination: str | os.PathLike[str]) -> None:
    """Extract a ZIP archive after validating every member path."""

    destination_path = Path(destination).resolve()
    destination_path.mkdir(parents=True, exist_ok=True)
    for member in archive.infolist():
        _validate_archive_member(member.filename, destination_path)
    archive.extractall(destination_path)


def compress_zip(zip_path: str | os.PathLike[str], input_directory: str | os.PathLike[str]) -> None:
    input_path = Path(input_directory).resolve()
    with ZipFile(zip_path, 'w', ZIP_DEFLATED) as archive:
        for file_path in input_path.rglob('*'):
            if file_path.is_file():
                archive.write(file_path, file_path.relative_to(input_path))


class BootImageWorkspace:
    """Unpack and repack one boot image in its containing directory."""

    def __init__(self, boot_path: str | os.PathLike[str]):
        self.boot_path = Path(boot_path).resolve()
        self.boot_directory = self.boot_path.parent
        self._previous_cwd: str | None = None

    def __enter__(self) -> 'BootImageWorkspace':
        self._previous_cwd = os.getcwd()
        os.chdir(self.boot_directory)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> bool:
        if self._previous_cwd is not None:
            os.chdir(self._previous_cwd)
        return False

    def unpack(self) -> None:
        with self:
            unpack_bootimg(str(self.boot_path))

    def repack(self) -> None:
        with self:
            boot_info_path = Path('bootinfo.txt')
            try:
                values = self._read_boot_info(boot_info_path)
            except (OSError, UnicodeError, ValueError) as exc:
                raise ValueError(f'Invalid bootinfo.txt in {self.boot_directory}: {exc}') from exc
            repack_bootimg(
                values['base'],
                values['cmdline'],
                values['page_size'],
                values['padding_size'],
                None,
            )

    @staticmethod
    def _read_boot_info(path: Path) -> dict[str, str]:
        values: dict[str, str] = {}
        with path.open(encoding='ascii') as file_handle:
            for line_number, raw_line in enumerate(file_handle, start=1):
                line = raw_line.lstrip('\x00').rstrip()
                if not line:
                    continue
                if ':' not in line:
                    raise ValueError(f'line {line_number} has no key separator')
                key, value = line.split(':', 1)
                key = key.strip()
                if not key:
                    raise ValueError(f'line {line_number} has an empty key')
                values[key] = value

        required_keys = {'base', 'cmdline', 'page_size', 'padding_size'}
        missing_keys = sorted(required_keys.difference(values))
        if missing_keys:
            raise ValueError(f'missing fields: {", ".join(missing_keys)}')
        return values


__all__ = [
    'BootImageWorkspace',
    'PropertyFile',
    'UnsafeArchiveMemberError',
    'UpdaterScript',
    'compress_zip',
    'safe_extract_zip',
]
