from __future__ import annotations

FORMAT_RAW_IMAGE = "common_technical_choice_format_raw_image"
FORMAT_SPARSE_IMAGE = "common_technical_choice_format_sparse_image"
FORMAT_DAT = "common_technical_choice_format_dat"
FORMAT_BROTLI_DAT = "common_technical_choice_format_brotli_dat"
FORMAT_XZ_DAT = "common_technical_choice_format_xz_dat"
FORMAT_IMG = "common_technical_choice_format_img"
FORMAT_PAYLOAD = "common_technical_choice_format_payload"
FORMAT_SUPER = "common_technical_choice_format_super"
FORMAT_UPDATE_APP = "common_technical_choice_format_update_app"
FORMAT_ZSTD = "common_technical_choice_format_zstd"
FORMAT_ZIP = "common_technical_choice_format_zip"

FILESYSTEM_EXT4 = "common_technical_choice_filesystem_ext4"
FILESYSTEM_F2FS = "common_technical_choice_filesystem_f2fs"
FILESYSTEM_EROFS = "common_technical_choice_filesystem_erofs"

IMAGE_BOOT = "common_technical_choice_image_boot"
IMAGE_RECOVERY = "common_technical_choice_image_recovery"
IMAGE_VENDOR_BOOT = "common_technical_choice_image_vendor_boot"

PACKER_MAKE_EXT4FS = "common_technical_choice_packer_make_ext4fs"
PACKER_MKE2FS_E2FSDROID = "common_technical_choice_packer_mke2fs_e2fsdroid"

COMPRESSION_LZ4 = "common_technical_choice_compression_lz4"
COMPRESSION_LZ4HC = "common_technical_choice_compression_lz4hc"
COMPRESSION_LZMA = "common_technical_choice_compression_lzma"
COMPRESSION_DEFLATE = "common_technical_choice_compression_deflate"
COMPRESSION_ZSTD = "common_technical_choice_compression_zstd"

SUPER_GROUP_QTI_DYNAMIC = "common_technical_choice_super_group_qti_dynamic"
SUPER_GROUP_MAIN = "common_technical_choice_super_group_main"
SUPER_GROUP_MOTOROLA = "common_technical_choice_super_group_motorola"

ARCH_ARM64_V8A = "common_technical_choice_arch_arm64_v8a"
ARCH_ARMEABI_V7A = "common_technical_choice_arch_armeabi_v7a"
ARCH_X86 = "common_technical_choice_arch_x86"
ARCH_X86_64 = "common_technical_choice_arch_x86_64"

ENCODING_UTF8 = "common_technical_choice_encoding_utf8"
ENCODING_GBK = "common_technical_choice_encoding_gbk"
ENCODING_GB2312 = "common_technical_choice_encoding_gb2312"
ENCODING_UTF16 = "common_technical_choice_encoding_utf16"

UNIT_B = "common_technical_choice_unit_b"
UNIT_KB = "common_technical_choice_unit_kb"
UNIT_MB = "common_technical_choice_unit_mb"
UNIT_GB = "common_technical_choice_unit_gb"
UNIT_TB = "common_technical_choice_unit_tb"
UNIT_PB = "common_technical_choice_unit_pb"
UNIT_KIB = "common_technical_choice_unit_kib"
UNIT_MIB = "common_technical_choice_unit_mib"
UNIT_GIB = "common_technical_choice_unit_gib"
UNIT_TIB = "common_technical_choice_unit_tib"
UNIT_EB = "common_technical_choice_unit_eb"

THEME_LIGHT = "common_technical_choice_theme_light"
THEME_DARK = "common_technical_choice_theme_dark"

MAGISK_NAME = "common_technical_choice_magisk_name"
VBMETA_NAME = "common_technical_choice_vbmeta_name"
FS_CONFIG_NAME = "common_technical_choice_fs_config_name"
FILE_CONTEXTS_NAME = "common_technical_choice_file_contexts_name"

FILE_TYPE_7Z = "common_technical_choice_file_type_7z"
FILE_TYPE_OZIP = "common_technical_choice_file_type_ozip"
FILE_TYPE_GPT = "common_technical_choice_file_type_gpt"
FILE_TYPE_SPLASH = "common_technical_choice_file_type_splash"
FILE_TYPE_DTBO = "common_technical_choice_file_type_dtbo"
FILE_TYPE_DTB = "common_technical_choice_file_type_dtb"
FILE_TYPE_EXE = "common_technical_choice_file_type_exe"
FILE_TYPE_ELF = "common_technical_choice_file_type_elf"
FILE_TYPE_AVB_FOOTER = "common_technical_choice_file_type_avb_footer"
FILE_TYPE_BZIP2 = "common_technical_choice_file_type_bzip2"
FILE_TYPE_CHROMEOS = "common_technical_choice_file_type_chromeos"
FILE_TYPE_GZIP = "common_technical_choice_file_type_gzip"
FILE_TYPE_LZ4_LEGACY = "common_technical_choice_file_type_lz4_legacy"
FILE_TYPE_ZOPFLI = "common_technical_choice_file_type_zopfli"
FILE_TYPE_LZ4_LG = "common_technical_choice_file_type_lz4_lg"
FILE_TYPE_PNG = "common_technical_choice_file_type_png"
FILE_TYPE_LOGO = "common_technical_choice_file_type_logo"
FILE_TYPE_RK_RESOURCE = "common_technical_choice_file_type_rk_resource"
FILE_TYPE_KDZ = "common_technical_choice_file_type_kdz"
FILE_TYPE_DZ = "common_technical_choice_file_type_dz"
FILE_TYPE_MACOS_BINARY = "common_technical_choice_file_type_macos_binary"
FILE_TYPE_PAC = "common_technical_choice_file_type_pac"
FILE_TYPE_NTPI = "common_technical_choice_file_type_ntpi"
FILE_TYPE_AMLOGIC = "common_technical_choice_file_type_amlogic"
FILE_TYPE_ROMFS = "common_technical_choice_file_type_romfs"
FILE_TYPE_UBI = "common_technical_choice_file_type_ubi"
FILE_TYPE_SQUASHFS = "common_technical_choice_file_type_squashfs"
FILE_TYPE_JFFS2 = "common_technical_choice_file_type_jffs2"
FILE_TYPE_RKFW = "common_technical_choice_file_type_rkfw"
FILE_TYPE_RKAF = "common_technical_choice_file_type_rkaf"
FILE_TYPE_GUOKE_LOGO = "common_technical_choice_file_type_guoke_logo"
FILE_TYPE_TAR = "common_technical_choice_file_type_tar"
FILE_TYPE_UNKNOWN = "common_technical_choice_file_type_unknown"
FILE_TYPE_EMPTY = "common_technical_choice_file_type_empty"
FILE_TYPE_FILE_NOT_FOUND = "common_technical_choice_file_type_file_not_found"

__all__ = [name for name in globals() if name.isupper()]
