from __future__ import annotations

CANCEL_BUTTON = "project_pack_partition_window_cancel_button"
PACK_BUTTON = "project_pack_partition_window_pack_button"
START_PROJECT_REQUIRED_MESSAGE = (
    "project_pack_partition_window_start_project_required_message"
)
PACK_PROJECT_REQUIRED_MESSAGE = (
    "project_pack_partition_window_pack_project_required_message"
)
BROTLI_NAME = "project_pack_partition_window_brotli_name"
UTC_LABEL = "project_pack_partition_window_utc_label"
FS_CONVERTER_CHECKBOX = "project_pack_partition_window_fs_converter_checkbox"
FS_CONVERT_ARROW = "project_pack_partition_window_fs_convert_arrow"
CUSTOM_SIZE_OK_BUTTON = "project_pack_partition_custom_size_dialog_ok_button"

PROJECT_PACK_PARTITION_CUSTOM_SIZE_DIALOG_MODIFY_SIZE = 'project_pack_partition_custom_size_dialog_modify_size'

PROJECT_PACK_PARTITION_WINDOW_ADDITIONAL_SETTINGS = 'project_pack_partition_window_additional_settings'
PROJECT_PACK_PARTITION_WINDOW_AUTOMATIC = 'project_pack_partition_window_automatic'
PROJECT_PACK_PARTITION_WINDOW_COMPRESSION_LEVEL_FORMAT = 'project_pack_partition_window_compression_level_format'
PROJECT_PACK_PARTITION_WINDOW_COMPRESSION_METHOD = 'project_pack_partition_window_compression_method'
PROJECT_PACK_PARTITION_WINDOW_EROFS_LEVEL_FORMAT = 'project_pack_partition_window_erofs_level_format'
PROJECT_PACK_PARTITION_WINDOW_EROFS_OPTIONS = 'project_pack_partition_window_erofs_options'
PROJECT_PACK_PARTITION_WINDOW_EXT4_OPTIONS = 'project_pack_partition_window_ext4_options'
PROJECT_PACK_PARTITION_WINDOW_IMAGE_SIZE_LABEL = 'project_pack_partition_window_image_size_label'
PROJECT_PACK_PARTITION_WINDOW_MODIFY_SIZE = 'project_pack_partition_window_modify_size'
PROJECT_PACK_PARTITION_WINDOW_OLD_KERNEL_SUPPORT = 'project_pack_partition_window_old_kernel_support'
PROJECT_PACK_PARTITION_WINDOW_OUTPUT_FORMAT_LABEL = 'project_pack_partition_window_output_format_label'
PROJECT_PACK_PARTITION_WINDOW_PACK_OPTIONS = 'project_pack_partition_window_pack_options'
PROJECT_PACK_PARTITION_WINDOW_PACKER_LABEL = 'project_pack_partition_window_packer_label'
PROJECT_PACK_PARTITION_WINDOW_PARTITIONS_TO_PACK = 'project_pack_partition_window_partitions_to_pack'
PROJECT_PACK_PARTITION_WINDOW_PATCH_VBMETA = 'project_pack_partition_window_patch_vbmeta'
PROJECT_PACK_PARTITION_WINDOW_REMOVE_ORIGINAL_FILE = 'project_pack_partition_window_remove_original_file'
PROJECT_PACK_PARTITION_WINDOW_SAME_AS_ORIGINAL = 'project_pack_partition_window_same_as_original'

__all__ = [name for name in globals() if name.isupper()]
