"""Presentation ports for the Plugin Store Tk surface."""

from __future__ import annotations

from collections.abc import Callable, Sequence
from tkinter import ttk
from typing import Protocol, TypeAlias


class PluginCatalogItemProtocol(Protocol):
    @property
    def plugin_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def author(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def description(self) -> str: ...
    @property
    def files(self) -> tuple[str, ...]: ...
    @property
    def dependencies(self) -> tuple[str, ...]: ...


class PluginStateChangedEventProtocol(Protocol):
    @property
    def plugin_id(self) -> str | None: ...
    @property
    def refresh_store(self) -> bool: ...


class StoreInstallResultProtocol(Protocol):
    @property
    def ok(self) -> bool: ...
    @property
    def error_kind(self) -> str: ...
    @property
    def error_reason(self) -> str: ...
    @property
    def failing_dependency_id(self) -> str: ...


class PluginStoreFetchResultProtocol(Protocol):
    @property
    def items(self) -> tuple[PluginCatalogItemProtocol, ...]: ...
    @property
    def error_text(self) -> str: ...
    @property
    def error_title(self) -> str: ...
    @property
    def ok(self) -> bool: ...


PluginUninstallResultView: TypeAlias = tuple[bool, str, list[str]]
StoreControls: TypeAlias = tuple[ttk.Button, ttk.Button]


class StoreViewStateProtocol(Protocol):
    def replace_catalog(self, items: tuple[PluginCatalogItemProtocol, ...]) -> None: ...
    def catalog_items(self) -> tuple[PluginCatalogItemProtocol, ...]: ...
    def controls_for(self, plugin_id: str) -> StoreControls | None: ...
    def register_controls(
        self,
        plugin_id: str,
        install_button: ttk.Button,
        uninstall_button: ttk.Button,
    ) -> None: ...
    def visible_plugin_ids(self) -> tuple[str, ...]: ...
    def app_frame_for(self, plugin_id: str) -> ttk.LabelFrame | None: ...
    def app_info_ids(self) -> tuple[str, ...]: ...
    def app_info_items(self) -> tuple[tuple[str, ttk.LabelFrame], ...]: ...
    def set_app_frame(self, plugin_id: str, frame: ttk.LabelFrame) -> None: ...
    def clear_catalog_widgets(self) -> None: ...


class StoreNotifierProtocol(Protocol):
    def show(
        self,
        message: str | None = None,
        color: str | None = None,
        *,
        text: str | None = None,
        title: str | None = None,
        master: object | None = None,
    ) -> object: ...


class StoreHostPortProtocol(Protocol):
    @property
    def state(self) -> StoreViewStateProtocol: ...

    @property
    def is_alive(self) -> Callable[[], bool]: ...

    @property
    def is_plugin_installed(self) -> Callable[[str], bool]: ...


class ClosableBindingProtocol(Protocol):
    def close(self) -> None: ...


class StoreCatalogProtocol(Protocol):
    def search_apps(self) -> None: ...
    def add_app(self, items: tuple[PluginCatalogItemProtocol, ...]) -> None: ...
    def clear(self) -> None: ...


class StoreLayoutProtocol(Protocol):
    def on_mousewheel_canvas(self, event: object) -> None: ...
    def on_label_frame_configure(self, event: object | None = None) -> None: ...
    def on_canvas_configure(self, event: object) -> None: ...


class StoreWindowControllerProtocol(Protocol):
    def open(self) -> None: ...
    def close(self) -> None: ...
    def start_download_async(
        self,
        files: tuple[str, ...],
        size: int,
        plugin_id: str,
        dependencies: tuple[str, ...],
    ) -> bool: ...
    def start_uninstall_async(self, plugin_id: str) -> bool: ...
    def consume_plugin_events(
        self,
        events: Sequence[PluginStateChangedEventProtocol],
    ) -> None: ...
    def modify_repo(self) -> object: ...
    def request_db_refresh(self, refresh: bool = False) -> bool: ...


class StoreCompositionProtocol(Protocol):
    @property
    def event_binding(self) -> ClosableBindingProtocol: ...

    @property
    def catalog(self) -> StoreCatalogProtocol: ...

    @property
    def layout(self) -> StoreLayoutProtocol: ...

    @property
    def controller(self) -> StoreWindowControllerProtocol: ...


class StoreSessionProtocol(Protocol):
    def open(self) -> None: ...
    def close(self) -> None: ...
    def ensure_background_plugin_load(self) -> None: ...


class StoreStateControllerProtocol(Protocol):
    def consume_events(self, events: list[PluginStateChangedEventProtocol]) -> None: ...
    def refresh_visible_plugin_states(self) -> None: ...
    def update_plugin_state(self, plugin_id: str) -> bool: ...
    def apply_uninstall_result(
        self,
        plugin_id: str,
        result: PluginUninstallResultView,
    ) -> None: ...
    def mark_installing(self, plugin_id: str) -> None: ...
    def update_install_progress(self, plugin_id: str, percentage: int) -> None: ...
    def apply_install_result(
        self,
        plugin_id: str,
        display_name: str,
        result: StoreInstallResultProtocol,
    ) -> None: ...


class StoreInstallControllerProtocol(Protocol):
    def start(
        self,
        files: tuple[str, ...],
        size: int,
        plugin_id: str,
        dependencies: tuple[str, ...],
        *,
        on_started: Callable[[str], None],
        on_progress: Callable[[str, int], None],
        on_finished: Callable[[str, str, StoreInstallResultProtocol], None],
    ) -> bool: ...


class StoreUninstallControllerProtocol(Protocol):
    def start(self, plugin_id: str) -> bool: ...


class StoreFetchControllerProtocol(Protocol):
    def apply_result(self, result: PluginStoreFetchResultProtocol) -> bool: ...
    def handle_error(self, exc: Exception) -> bool: ...
    def fetch_db(self, refresh: bool = False) -> PluginStoreFetchResultProtocol: ...
    def request_initial_refresh(self, initialize: Callable[[], object]) -> bool: ...
    def request_refresh(self, refresh: bool = False) -> bool: ...


__all__ = [name for name in globals() if name.endswith(("Protocol", "View"))]
